"""initial schema

Revision ID: 971bd8460cb2
Revises: 
Create Date: 2026-09-11 11:24:53.521104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971bd8460cb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('app', sa.String(), nullable=False),
    sa.Column('raw_asr', sa.Text(), nullable=False),
    sa.Column('llm_formatted', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('hey_kivi_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('tools_called', sa.JSON(), nullable=True),
    sa.Column('memories_used', sa.JSON(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('abstained', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('factual', 'episodic', 'preference', name='memorytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'deleted', 'overridden', name='memorystatus'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=True),
    sa.Column('action', sa.Enum('created', 'retrieved', 'updated', 'rejected', 'decayed', 'deleted', name='eventaction'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_provenance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('dictation_id', sa.String(), nullable=False),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dictation_id'], ['dictations.id'], ),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_provenance')
    op.drop_table('memory_events')
    op.drop_table('memories')
    op.drop_table('hey_kivi_turns')
    op.drop_table('dictations')
    op.drop_table('users')
    # ### end Alembic commands ###
